import type { NextPage } from "next";
import { motion, useScroll } from "framer-motion";
import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";

const Home: NextPage = () => {
  const { scrollYProgress } = useScroll();

  return (
    <div>
      <Head>
        <title>Peter Chin | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        className="fixed bottom-0 left-0 right-0 h-[10px] bg-green-600 origin-[0%]"
        style={{ scaleX: scrollYProgress }}
      />

      <Navbar />
      <Main />
      <About />
      <Skills />
    </div>
  );
};

export default Home;
